# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - name: "py37-django-22"
      python: "3.7"
      env: TOX_ENV=py37-django-22
    - name: "py37-django-30"
      python: "3.7"
      env: TOX_ENV=py37-django-30
    - name: "py37-django-31"
      python: "3.7"
      env: TOX_ENV=py37-django-31
    - name: "py37-django-32"
      python: "3.7"
      env: TOX_ENV=py37-django-32
    - name: "py38-django-22"
      python: "3.8"
      env: TOX_ENV=py38-django-22
    - name: "py38-django-30"
      python: "3.8"
      env: TOX_ENV=py38-django-30
    - name: "py38-django-31"
      python: "3.8"
      env: TOX_ENV=py38-django-31
    - name: "py38-django-32"
      python: "3.8"
      env: TOX_ENV=py38-django-32
    - name: "py39-django-22"
      python: "3.9"
      env: TOX_ENV=py39-django-22
    - name: "py39-django-30"
      python: "3.9"
      env: TOX_ENV=py39-django-30
    - name: "py39-django-31"
      python: "3.9"
      env: TOX_ENV=py39-django-31
    - name: "py39-django-32"
      python: "3.9"
      env: TOX_ENV=py39-django-32
  fast_finish: true

#before_install:
#  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
#  - sudo apt-get --quiet update
#  - sudo apt-get install --yes libgdal-dev gdal-bin libspatialite7 libspatialite-dev libsqlite3-mod-spatialite
# command to install dependencies, e.g.
# pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
